backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "public/images" # Where media will be stored
public_folder: "/images" # Where media is accessed in the public URL

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "featuredImage", widget: "image", required: false }
      - {
          label: "Project Images",
          name: "gallery",
          widget: "list",
          summary: "{{fields.image}}",
          field: { label: "Image", name: "image", widget: "image", media_folder: "/public/images/{{slug}}", public_folder: "/images/{{slug}}" }
        }
      - { label: "Content", name: "body", widget: "markdown" }