backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

# Media folder settings - this is where we organize images per event
media_folder: "public/images"
public_folder: "/images"


collections:
  - name: "events"
    label: "Events"
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Event Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredImage", widget: "image", required: false }
      - {
          label: "Event Images",
          name: "images",
          widget: "list",
          summary: "{{fields.image}}",
          field: { label: "Image", name: "image", widget: "image", media_folder: "/public/images/{{slug}}", public_folder: "/images/{{slug}}" }
        }
      - { label: "Description", name: "description", widget: "text", required: false }